name: Build

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-24.04]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install dependencies from apt
      run: |
        sudo apt update
        sudo apt install -y make clang llvm libbpf-dev linux-tools-generic
    
    - name: Compile with Make
      run: |
        make CORE=1 static
    
    - name: Upload x64 binary
      uses: actions/upload-artifact@v4
      with:
          name: lemon.x86_64
          path: "lemon.x86_64"
      continue-on-error: true

    - name: Upload ARM64 binary
      uses: actions/upload-artifact@v4
      with:
          name: lemon.aarch64
          path: "lemon.aarch64"
      continue-on-error: true