name: Build

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-24.04]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install dependencies from apt
      run: |
        sudo apt update
        sudo apt install -y make llvm libbpf-dev libcap-dev linux-tools-generic
    
    - name: Compile with Make
      run: |
        make MODE=core STATIC=1
    
    - name: Upload x64 CORE binary
      uses: actions/upload-artifact@v4
      with:
          name: lemon.core.x86_64
          path: "lemon.core.x86_64"
      continue-on-error: true

    - name: Upload ARM64 CORE binary
      uses: actions/upload-artifact@v4
      with:
          name: lemon.core.aarch64
          path: "lemon.core.aarch64"
      continue-on-error: true

    - name: Compile with Make
      run: |
        make MODE=nocoreuni STATIC=1
    
    - name: Upload x64 NO-CORE universal binary
      uses: actions/upload-artifact@v4
      with:
          name: lemon.nocoreuni.x86_64
          path: "lemon.nocoreuni.x86_64"
      continue-on-error: true

    - name: Upload ARM64 NO-CORE universal binary
      uses: actions/upload-artifact@v4
      with:
          name: lemon.nocoreuni.aarch64
          path: "lemon.nocoreuni.aarch64"
      continue-on-error: true

  run:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-24.04]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Run dump to disk
        run: |
          sudo chmod +x ./lemon.core.$(uname -m)/lemon.core.$(uname -m)
          sudo ./lemon.core.$(uname -m)/lemon.core.$(uname -m) -d /dev/null
      - name: Run dump to disk
        run: |
          sudo chmod +x ./lemon.nocoreuni.$(uname -m)/lemon.nocoreuni.$(uname -m)
          sudo ./lemon.nocoreuni.$(uname -m)/lemon.nocoreuni.$(uname -m) -d /dev/null
